### ISSUE TITLE
В гите должна быть сама папка с проектом, а не подпапка

### ISSUE THREAD

**Issue by coursar** [AlexeiRusov/git#1]
Т.е. папки `Homework` быть не должно

**Comment by AlexeiRusov** [comment]
@coursar что то не получается, пытался новый репозиторий создать - не получилось. а в рамках этого репозитория с сохранением Issues тоже не знаю как(( т.е. как на один корень всё это вынести?

**Comment by coursar** [comment]
Это на будущее, на паре рассмотрим.
