### ISSUE TITLE
Откуда берутся 1000 и 100? Из кода непонятно назначение. Нужно вынести в переменные с говорящими именами.

### ISSUE THREAD

**Issue by coursar** [AlexeiRusov/git#3]
https://github.com/AlexeiRusov/git/blob/c1112e72341eed8159520dd528d45c937636046b/Homework/script.js#L4

**Comment by AlexeiRusov** [comment]
@coursar Какой то тупик.... Хотя бы в том направлении двигаюсь?
1000 обозвать как коэффициент для округления (по англ. конечно)
а 100 назвать как, например, перевод в баллы?
так?
Или  вообще надо все переделать используя Math.floor?

**Comment by AlexeiRusov** [comment]
Вроде как поправил, прошу проверить
